use expense_tracker;
insert into income (id, stock_income, income_amount, user_id) values (1, 'Constellation Brands Inc', '$152639.82', 1);
insert into income (id, stock_income, income_amount, user_id) values (2, 'Tellurian Inc.', '$543799.51', 2);
insert into income (id, stock_income, income_amount, user_id) values (3, 'AgroFresh Solutions, Inc.', '$301220.64', 3);
insert into income (id, stock_income, income_amount, user_id) values (4, 'Diana Containerships Inc.', '$597641.84', 4);
insert into income (id, stock_income, income_amount, user_id) values (5, 'NeoPhotonics Corporation', '$202689.12', 5);
insert into income (id, stock_income, income_amount, user_id) values (6, 'Shell Midstream Partners, L.P.', '$795707.24', 6);
insert into income (id, stock_income, income_amount, user_id) values (7, 'Penns Woods Bancorp, Inc.', '$721012.90', 7);
insert into income (id, stock_income, income_amount, user_id) values (8, 'Ames National Corporation', '$435147.02', 8);
insert into income (id, stock_income, income_amount, user_id) values (9, 'Timken Steel Corporation', '$365919.40', 9);
insert into income (id, stock_income, income_amount, user_id) values (10, 'Aberdeen Singapore Fund, Inc.', '$546632.48', 10);
insert into income (id, stock_income, income_amount, user_id) values (11, 'VelocityShares 3x Inverse Silver ETN', '$537011.62', 11);
insert into income (id, stock_income, income_amount, user_id) values (12, 'BlueLinx Holdings Inc.', '$610241.49', 12);
insert into income (id, stock_income, income_amount, user_id) values (13, 'Public Service Enterprise Group Incorporated', '$748093.36', 13);
insert into income (id, stock_income, income_amount, user_id) values (14, '1st Source Corporation', '$770329.28', 14);
insert into income (id, stock_income, income_amount, user_id) values (15, 'GP Investments Acquisition Corp.', '$226193.98', 15);
insert into income (id, stock_income, income_amount, user_id) values (16, 'Second Sight Medical Products, Inc.', '$145316.82', 16);
insert into income (id, stock_income, income_amount, user_id) values (17, 'Stepan Company', '$268139.48', 17);
insert into income (id, stock_income, income_amount, user_id) values (18, 'Umpqua Holdings Corporation', '$104446.13', 18);
insert into income (id, stock_income, income_amount, user_id) values (19, 'Tilly''s, Inc.', '$277003.55', 19);
insert into income (id, stock_income, income_amount, user_id) values (20, 'Zimmer Biomet Holdings, Inc.', '$839386.83', 20);
insert into income (id, stock_income, income_amount, user_id) values (21, 'DDR Corp.', '$219824.74', 21);
insert into income (id, stock_income, income_amount, user_id) values (22, 'Colony NorthStar, Inc.', '$687866.34', 22);
insert into income (id, stock_income, income_amount, user_id) values (23, 'Vanguard Intermediate-Term Corporate Bond ETF', '$787759.73', 23);
insert into income (id, stock_income, income_amount, user_id) values (24, 'Concord Medical Services Holdings Limited', '$311707.10', 24);
insert into income (id, stock_income, income_amount, user_id) values (25, 'MTGE Investment Corp.', '$832600.13', 25);
insert into income (id, stock_income, income_amount, user_id) values (26, 'Microsoft Corporation', '$91302.62', 26);
insert into income (id, stock_income, income_amount, user_id) values (27, 'Hyatt Hotels Corporation', '$959530.56', 27);
insert into income (id, stock_income, income_amount, user_id) values (28, 'Stewart Information Services Corporation', '$661395.01', 28);
insert into income (id, stock_income, income_amount, user_id) values (29, 'Synthesis Energy Systems, Inc.', '$406429.69', 29);
insert into income (id, stock_income, income_amount, user_id) values (30, 'Henry Schein, Inc.', '$52862.59', 30);
insert into income (id, stock_income, income_amount, user_id) values (31, 'TiVo Corporation', '$905762.78', 31);
insert into income (id, stock_income, income_amount, user_id) values (32, 'Teekay Tankers Ltd.', '$130780.97', 32);
insert into income (id, stock_income, income_amount, user_id) values (33, 'Upland Software, Inc.', '$748284.66', 33);
insert into income (id, stock_income, income_amount, user_id) values (34, 'YRC Worldwide, Inc.', '$129854.27', 34);
insert into income (id, stock_income, income_amount, user_id) values (35, 'LMI Aerospace, Inc.', '$915590.88', 35);
insert into income (id, stock_income, income_amount, user_id) values (36, 'Protagonist Therapeutics, Inc.', '$212746.34', 36);
insert into income (id, stock_income, income_amount, user_id) values (37, 'United Technologies Corporation', '$17061.45', 37);
insert into income (id, stock_income, income_amount, user_id) values (38, 'Bank of the Ozarks', '$632938.61', 38);
insert into income (id, stock_income, income_amount, user_id) values (39, 'Dominion Energy Midstream Partners, LP', '$136646.40', 39);
insert into income (id, stock_income, income_amount, user_id) values (40, 'Interactive Brokers Group, Inc.', '$938777.68', 40);
insert into income (id, stock_income, income_amount, user_id) values (41, 'Voya Emerging Markets High Income Dividend Equity Fund', '$55652.01', 41);
insert into income (id, stock_income, income_amount, user_id) values (42, 'Invesco California Value Municipal Income Trust', '$581114.00', 42);
insert into income (id, stock_income, income_amount, user_id) values (43, 'iShares MSCI ACWI ex US Index Fund', '$224798.19', 43);
insert into income (id, stock_income, income_amount, user_id) values (44, 'Resource Capital Corp.', '$693718.03', 44);
insert into income (id, stock_income, income_amount, user_id) values (45, 'News Corporation', '$512260.31', 45);
insert into income (id, stock_income, income_amount, user_id) values (46, 'Orrstown Financial Services Inc', '$298571.77', 46);
insert into income (id, stock_income, income_amount, user_id) values (47, 'Nuveen Tax-Advantaged Dividend Growth Fund', '$794799.24', 47);
insert into income (id, stock_income, income_amount, user_id) values (48, 'Altisource Portfolio Solutions S.A.', '$505069.50', 48);
insert into income (id, stock_income, income_amount, user_id) values (49, 'Morgan Stanley', '$830176.52', 49);
insert into income (id, stock_income, income_amount, user_id) values (50, 'Coach, Inc.', '$621400.00', 50);
insert into income (id, stock_income, income_amount, user_id) values (51, 'Torchlight Energy Resources, Inc.', '$728924.56', 51);
insert into income (id, stock_income, income_amount, user_id) values (52, 'Oshkosh Corporation', '$396418.83', 52);
insert into income (id, stock_income, income_amount, user_id) values (53, 'ARMOUR Residential REIT, Inc.', '$426577.85', 53);
insert into income (id, stock_income, income_amount, user_id) values (54, 'Cherry Hill Mortgage Investment Corporation', '$290355.08', 54);
insert into income (id, stock_income, income_amount, user_id) values (55, '1st Constitution Bancorp (NJ)', '$300016.90', 55);
insert into income (id, stock_income, income_amount, user_id) values (56, 'Ohio Valley Banc Corp.', '$496978.55', 56);
insert into income (id, stock_income, income_amount, user_id) values (57, 'PartnerRe Ltd.', '$419847.16', 57);
insert into income (id, stock_income, income_amount, user_id) values (58, 'Nova Lifestyle, Inc', '$212030.28', 58);
insert into income (id, stock_income, income_amount, user_id) values (59, 'Atlanticus Holdings Corporation', '$313415.34', 59);
insert into income (id, stock_income, income_amount, user_id) values (60, 'BioCryst Pharmaceuticals, Inc.', '$534003.93', 60);
insert into income (id, stock_income, income_amount, user_id) values (61, 'JPMorgan China Region Fund, Inc.', '$380093.79', 61);
insert into income (id, stock_income, income_amount, user_id) values (62, 'LSI Industries Inc.', '$600031.36', 62);
insert into income (id, stock_income, income_amount, user_id) values (63, 'Silgan Holdings Inc.', '$876163.77', 63);
insert into income (id, stock_income, income_amount, user_id) values (64, 'First Trust RiverFront Dynamic Developed International ETF', '$189239.59', 64);
insert into income (id, stock_income, income_amount, user_id) values (65, 'American Homes 4 Rent', '$726463.70', 65);
insert into income (id, stock_income, income_amount, user_id) values (66, 'BlackRock Utility and Infrastructure Trust', '$275879.94', 66);
insert into income (id, stock_income, income_amount, user_id) values (67, 'Finjan Holdings, Inc.', '$730260.61', 67);
insert into income (id, stock_income, income_amount, user_id) values (68, 'LendingClub Corporation', '$883744.45', 68);
insert into income (id, stock_income, income_amount, user_id) values (69, 'Kayne Anderson Acquisition Corp.', '$671331.52', 69);
insert into income (id, stock_income, income_amount, user_id) values (70, 'Ames National Corporation', '$441678.99', 70);
insert into income (id, stock_income, income_amount, user_id) values (71, 'Safeguard Scientifics, Inc.', '$47782.89', 71);
insert into income (id, stock_income, income_amount, user_id) values (72, 'Banco Santander, S.A.', '$381743.46', 72);
insert into income (id, stock_income, income_amount, user_id) values (73, 'The Goodyear Tire & Rubber Company', '$946053.63', 73);
insert into income (id, stock_income, income_amount, user_id) values (74, 'TG Therapeutics, Inc.', '$260552.81', 74);
insert into income (id, stock_income, income_amount, user_id) values (75, 'Motorcar Parts of America, Inc.', '$276091.47', 75);
insert into income (id, stock_income, income_amount, user_id) values (76, 'Union Pacific Corporation', '$773406.16', 76);
insert into income (id, stock_income, income_amount, user_id) values (77, 'SunTrust Banks, Inc.', '$56180.70', 77);
insert into income (id, stock_income, income_amount, user_id) values (78, 'Global X Robotics & Artificial Intelligence ETF', '$257669.71', 78);
insert into income (id, stock_income, income_amount, user_id) values (79, 'Howard Hughes Corporation (The)', '$149497.87', 79);
insert into income (id, stock_income, income_amount, user_id) values (80, 'North Atlantic Drilling Ltd.', '$480717.53', 80);
insert into income (id, stock_income, income_amount, user_id) values (81, 'VictoryShares US Small Cap Volatility Wtd ETF', '$592887.57', 81);
insert into income (id, stock_income, income_amount, user_id) values (82, 'Protective Life Corporation', '$515219.09', 82);
insert into income (id, stock_income, income_amount, user_id) values (83, 'Janus Henderson Group plc', '$917384.87', 83);
insert into income (id, stock_income, income_amount, user_id) values (84, 'TerraVia Holdings, Inc.', '$835694.37', 84);
insert into income (id, stock_income, income_amount, user_id) values (85, 'Hailiang Education Group Inc.', '$820571.97', 85);
insert into income (id, stock_income, income_amount, user_id) values (86, 'Accenture plc', '$663227.51', 86);
insert into income (id, stock_income, income_amount, user_id) values (87, 'Corporate Office Properties Trust', '$440603.28', 87);
insert into income (id, stock_income, income_amount, user_id) values (88, 'HV Bancorp, Inc.', '$772175.60', 88);
insert into income (id, stock_income, income_amount, user_id) values (89, 'Envestnet, Inc', '$459235.40', 89);
insert into income (id, stock_income, income_amount, user_id) values (90, 'Valvoline Inc.', '$398307.12', 90);
insert into income (id, stock_income, income_amount, user_id) values (91, 'SunTrust Banks, Inc.', '$740135.52', 91);
insert into income (id, stock_income, income_amount, user_id) values (92, 'Plexus Corp.', '$288158.94', 92);
insert into income (id, stock_income, income_amount, user_id) values (93, 'Sanderson Farms, Inc.', '$756423.69', 93);
insert into income (id, stock_income, income_amount, user_id) values (94, 'Corporate Asset Backed Corp CABCO', '$679907.60', 94);
insert into income (id, stock_income, income_amount, user_id) values (95, 'Blueknight Energy Partners L.P., L.L.C.', '$179782.98', 95);
insert into income (id, stock_income, income_amount, user_id) values (96, 'Cellectar Biosciences, Inc.', '$688253.36', 96);
insert into income (id, stock_income, income_amount, user_id) values (97, 'Great Plains Energy Inc', '$175226.71', 97);
insert into income (id, stock_income, income_amount, user_id) values (98, 'Chesapeake Energy Corporation', '$145618.30', 98);
insert into income (id, stock_income, income_amount, user_id) values (99, 'Cirrus Logic, Inc.', '$178597.69', 99);
insert into income (id, stock_income, income_amount, user_id) values (100, 'AAC Holdings, Inc.', '$883627.81', 100);